### ISSUE TITLE
Kodi - "Failed due to an invalid structure."

### ISSUE THREAD

**Issue by N-Erickson** [danlevan/scraper-kshow123#3]
Greetings!  Thank you for your work on this.

I am having an issue installing this in both Kodi 16.1 and 17.1 on two separate Windows 10 machines.

I receive an error when installing - "failed due to an invalid structure."  I've tried creating the zip file with the built in windows utility and 7-Zip.

I have also tried completely rebuilding the .xml file.  The same error persists.

Would you have any input on this issue?  Also, what version of Kodi have you used this with and what operating system?  

Thank you!

**Comment by KodiDroid** [comment]
I had the same issue installing on Windows. Download plugin.video.kshow123.zip from https://github.com/danlevan/scraper-kshow123/releases and edit the addon.xml file to allow all platforms (e.g. <platform>all</platform>).

**Comment by N-Erickson** [comment]
KodiDroid - Thank you for the assistance.  I have tried setting platform to all and windsx.  Neither worked.  I followed the official Kodi wiki as well, which recommends removing the platform section all together and it should function the same as "all."  None of these 3 options worked for me, I still receive the same error.

**Comment by KodiDroid** [comment]
Modifying the platform tag worked for me. I created a temporary fork of the project. Try https://github.com/KodiDroid/scraper-kshow123/releases/download/v1.1.3-alpha/plugin.video.kshow123.zip which has the change to the addon.xml file.

**Comment by N-Erickson** [comment]
KodiDroid - Thank you, your uploaded .zip worked for me.  I think the issue I was having now was with the compression of the zip file.  I used the Windows Utility, 7-Zip, and WinRAR.  None of the .zip files would work in Kodi for me.  Uploading the project files to github and downloading a .zip worked.

Thank you for the help!

**Comment by ashraw86** [comment]
@N-Erickson the problem was not the compression. It was rather the heirarchy created by compression. I was facing the same issue for 1 hour and suddenly I saw when we unzip and zip back the folder, the folder hierarchy increases by 2. So, instead of zipping the parent folder, I rather zipped the grandchild folder, renamed it as per convention and put it in kodi for installation. Voila ! it worked.

**Comment by SoaringSloth388** [comment]
@N-Erickson Hi, I do not knw a lot about files so could I please have a bit of help:)

**Comment by N-Erickson** [comment]
> @N-Erickson Hi, I do not knw a lot about files so could I please have a bit of help:)

I have not used this in approx 6 years, when I did, I used the linked version from kodidroid's comment:
 https://github.com/8lueberry/scraper-kshow123/issues/3#issuecomment-292691856
 
 Assuming it still works in Kodi, its available to download.
